# Generated by Django 4.1.2 on 2022-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-recently_viewed']},
        ),
        migrations.AddField(
            model_name='entry',
            name='recently_viewed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
