# Generated by Django 4.1.2 on 2022-10-21 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_entry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
