# Generated by Django 4.1.2 on 2022-10-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_alter_entry_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_created']},
        ),
    ]
